modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="roleplaymenu"
version="1.0"
displayName="Roleplay Start Menu Mod"
description='''Meniu de start pentru servere roleplay. Alege rolul la prima intrare.'''